Repository udacity/DSND_Term2, pull requests merged in 2021-03, with the labels that each got.

#11 fix typo: 'more than 75% if their missing values'
  lessons/CRISP_DM/A Look at the Data.ipynb
Labels: typo

#21 Rename files -> no question marks
  lessons/CRISP_DM/What Happened - Solution.ipynb
  lessons/CRISP_DM/What Happened.ipynb
Labels: improve classroom

#17 Corrected the calculate_stdev method name
  lessons/ObjectOrientedProgramming/JupyterNotebooks/3.OOP_code_gaussian_class/.ipynb_checkpoints/gaussian_code_exercise-checkpoint.ipynb
  lessons/ObjectOrientedProgramming/JupyterNotebooks/3.OOP_code_gaussian_class/gaussian_code_exercise.ipynb
  lessons/ObjectOrientedProgramming/JupyterNotebooks/4.OOP_code_magic_methods/.ipynb_checkpoints/magic_methods-checkpoint.ipynb
  lessons/ObjectOrientedProgramming/JupyterNotebooks/4.OOP_code_magic_methods/magic_methods.ipynb
Labels: typo

#15 docs: correct variable reference name.
  lessons/ETLPipelines/17_load_exercise/17_load_exercise.ipynb
Labels: typo

#12 Added small tolerance in the R2 test
  lessons/CRISP_DM/RemovingData.py
Labels: bug

#16 docs: Updated comments in the Jupyter notebook
  lessons/ETLPipelines/12_dummyvariables_exercise/12_dummyvariables_exercise-solution.ipynb
  lessons/ETLPipelines/12_dummyvariables_exercise/12_dummyvariables_exercise.ipynb
Labels: typo

#30 Fix broken requirement in lessons/WebDevelopment/AdvancedDataDashboardCode/world_bank_api_dashboard/requirements.txt
  lessons/WebDevelopment/AdvancedDataDashboardCode/world_bank_api_dashboard/requirements.txt
Labels: dependency update
